<a href="https://colab.research.google.com/github/mrymalsubhi/BankOfTheFutureProject/blob/main/BankOfTheFuture_Transforming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Importing libraries ðŸ“š:

In [ ]:
# Importing important libraries:
import pandas as pd
import numpy as np
from datetime import datetime
from scipy import stats

In [ ]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.10/dist-packages (0.17.9)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (67.7.2)
Requirement already satisfied: db-dtypes<2.0.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (1.1.1)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (1.23.5)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (1.5.3)
Requirement already satisfied: pyarrow<10.0dev,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (9.0.0)
Requirement already satisfied: pydata-google-auth in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (1.8.2)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (2.11.1)
Requirement already satisfied: google-auth>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (2.17.3)
Requirement already satisfied: google-auth-oauthlib>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (1.0.0)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (3.12.0)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0dev,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq) (2.23.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.10/dist-packages (from db-dtypes<2.0.0,>=0.3.1->pandas-gbq) (23.2)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (1.61.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (3.20.3)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (2.31.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.25.0->pandas-gbq) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.25.0->pandas-gbq) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.25.0->pandas-gbq) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth>=1.25.0->pandas-gbq) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib>=0.0.1->pandas-gbq) (1.3.1)
Requirement already satisfied: grpcio<2.0dev,>=1.47.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (1.59.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (1.22.3)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (2.3.3)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (2.6.0)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->pandas-gbq) (2023.3.post1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (1.48.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=1.27.2->pandas-gbq) (1.5.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.25.0->pandas-gbq) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->pandas-gbq) (2023.11.17)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.0.1->pandas-gbq) (3.2.2)

# 2. Cleaning  ðŸ§¼:

### 1.1 Devices table

In [ ]:

from google.colab import auth

auth.authenticate_user()
query = "SELECT * FROM  `data-analytics-bootcamp-363212.neo_bank.devices`"

df_devices = pd.read_gbq(query, project_id="data-analytics-bootcamp-363212")

In [ ]:
df_devices

      string_field_0 string_field_1
0              Apple      user_6809
1              Apple      user_3636
2              Apple       user_510
3              Apple      user_3468
4              Apple      user_7036
...              ...            ...
19426        Unknown     user_13531
19427        Unknown     user_12568
19428        Unknown     user_12296
19429        Unknown     user_19056
19430        Unknown     user_12199

[19431 rows x 2 columns]

In [ ]:
# renaming the column name
df_devices=df_devices.rename(columns={'string_field_0':'brand','string_field_1':'user_id'})
df_devices

         brand     user_id
0        Apple   user_6809
1        Apple   user_3636
2        Apple    user_510
3        Apple   user_3468
4        Apple   user_7036
...        ...         ...
19426  Unknown  user_13531
19427  Unknown  user_12568
19428  Unknown  user_12296
19429  Unknown  user_19056
19430  Unknown  user_12199

[19431 rows x 2 columns]

In [ ]:
df_devices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19431 entries, 0 to 19430
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   brand    19431 non-null  object
 1   user_id  19431 non-null  object
dtypes: object(2)
memory usage: 303.7+ KB

In [ ]:
# filling the 'unknown' values in the 'brand' column
counts = df_devices["brand"].value_counts()
unknown_count = counts["Unknown"]

apple_count = unknown_count // 2
android_count = unknown_count - apple_count

unknown_indexes = df_devices[df_devices["brand"] == "Unknown"].index
unknown_indexes = unknown_indexes.to_numpy()

if apple_count > 0:
    apple_indexes = np.random.choice(unknown_indexes, size=apple_count, replace=False)
    df_devices.loc[apple_indexes, "brand"] = "Apple"

if android_count > 0:
    remaining_indexes = np.setdiff1d(unknown_indexes, apple_indexes)
    android_indexes = np.random.choice(remaining_indexes, size=android_count, replace=False)
    df_devices.loc[android_indexes, "brand"] = "Android"

print(df_devices)

         brand     user_id
0        Apple   user_6809
1        Apple   user_3636
2        Apple    user_510
3        Apple   user_3468
4        Apple   user_7036
...        ...         ...
19426    Apple  user_13531
19427    Apple  user_12568
19428    Apple  user_12296
19429    Apple  user_19056
19430  Android  user_12199

[19431 rows x 2 columns]

In [ ]:
# removing unwanted row
df_devices = df_devices.drop(df_devices[df_devices['brand'] == 'brand'].index)

In [ ]:
df_devices

         brand     user_id
0        Apple   user_6809
1        Apple   user_3636
2        Apple    user_510
3        Apple   user_3468
4        Apple   user_7036
...        ...         ...
19426    Apple  user_13531
19427    Apple  user_12568
19428    Apple  user_12296
19429    Apple  user_19056
19430  Android  user_12199

[19430 rows x 2 columns]

### 1.2 Notifications table

In [ ]:
# importing the notifications table from google big query
query = "SELECT * FROM  `data-analytics-bootcamp-363212.neo_bank.notifications`"
df_notifications = pd.read_gbq(query, project_id="data-analytics-bootcamp-363212")

In [ ]:
# checking the null values
df_notifications.isnull().sum()

reason          0
channel         0
status          0
user_id         0
created_date    0
dtype: int64

In [ ]:
df_notifications.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121813 entries, 0 to 121812
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   reason        121813 non-null  object
 1   channel       121813 non-null  object
 2   status        121813 non-null  object
 3   user_id       121813 non-null  object
 4   created_date  121813 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), object(4)
memory usage: 4.6+ MB

In [ ]:
# converting the ['created_date'] from Timestamp to datetime

df_notifications['created_date'] = pd.to_datetime(df_notifications['created_date'])

# Extract date only
df_notifications['created_date'] = df_notifications['created_date'].dt.date

print(df_notifications['created_date'])

0         2018-10-14
1         2018-10-17
2         2018-10-14
3         2018-10-14
4         2018-10-14
             ...
121808    2019-01-26
121809    2019-01-26
121810    2019-01-27
121811    2019-01-28
121812    2019-01-27
Name: created_date, Length: 121813, dtype: object

In [ ]:
df_notifications

,reason,channel,status,user_id,created_date
0,METAL_RESERVE_PLAN,SMS,SENT,user_4703,2018-10-14
1,METAL_RESERVE_PLAN,SMS,SENT,user_2397,2018-10-17
2,METAL_RESERVE_PLAN,SMS,SENT,user_2411,2018-10-14
3,METAL_RESERVE_PLAN,SMS,SENT,user_1119,2018-10-14
4,METAL_RESERVE_PLAN,SMS,SENT,user_3499,2018-10-14
...,...,...,...,...,...
121808,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19156,2019-01-26
121809,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_18016,2019-01-26
121810,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_18016,2019-01-27
121811,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19023,2019-01-28
121812,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19156,2019-01-27

### 1.3 Transactions table

In [ ]:
# importing the transactions table from google big query

query = "SELECT * FROM  `data-analytics-bootcamp-363212.neo_bank.transactions`"
df_transactions = pd.read_gbq(query, project_id="data-analytics-bootcamp-363212")

In [ ]:
# converting the ['created_date'] from Timestamp to datetime

df_transactions['created_date'] = pd.to_datetime(df_transactions['created_date'])

# Extract date only
df_transactions['created_date'] = df_transactions['created_date'].dt.date

df_transactions

,transaction_id,transactions_type,transactions_currency,amount_usd,transactions_state,ea_cardholderpresence,ea_merchant_mcc,ea_merchant_city,ea_merchant_country,direction,user_id,created_date
0,transaction_1973,TOPUP,AED,6079.39,COMPLETED,None,NaN,None,None,INBOUND,user_4773,2018-08-13
1,transaction_508,TOPUP,AED,298.64,COMPLETED,None,NaN,None,None,INBOUND,user_4773,2018-09-06
2,transaction_33,TOPUP,AED,236.63,COMPLETED,None,NaN,None,None,INBOUND,user_4773,2018-10-04
3,transaction_1755306,EXCHANGE,AED,69.92,COMPLETED,None,NaN,None,None,OUTBOUND,user_10943,2018-12-07
4,transaction_940,EXCHANGE,AED,52.24,COMPLETED,None,NaN,None,None,OUTBOUND,user_1363,2018-12-28
...,...,...,...,...,...,...,...,...,...,...,...,...
2740070,transaction_1846709,CARD_PAYMENT,ZAR,651.84,DECLINED,TRUE,4816.0,Cape Town,ZAF,OUTBOUND,user_10000,2018-08-20
2740071,transaction_89487,CARD_PAYMENT,ZAR,7.14,COMPLETED,TRUE,7399.0,Rosebank,ZAF,OUTBOUND,user_598,2018-11-21
2740072,transaction_227881,CARD_PAYMENT,ZAR,12.69,COMPLETED,FALSE,7399.0,Broederstroom,ZAF,OUTBOUND,user_1051,2018-10-01
2740073,transaction_88782,CARD_PAYMENT,ZAR,3.44,COMPLETED,TRUE,7399.0,Rosebank,ZAF,OUTBOUND,user_598,2018-11-21
2740074,transaction_1846020,CARD_PAYMENT,ZAR,7.51,COMPLETED,FALSE,8661.0,Cape Town,ZAF,OUTBOUND,user_19085,2019-04-05

In [ ]:
df_transactions.isnull().sum()

transaction_id                 0
transactions_type              0
transactions_currency          0
amount_usd                     0
transactions_state             0
ea_cardholderpresence    1170594
ea_merchant_mcc          1158658
ea_merchant_city         1158794
ea_merchant_country      1158979
direction                      0
user_id                        0
created_date                   0
dtype: int64

In [ ]:
#deleting the ea_merchant_mcc	ea_merchant_city	ea_merchant_country

df_transactions = df_transactions.drop('ea_merchant_mcc' , axis = 1)
df_transactions = df_transactions.drop('ea_merchant_city' , axis = 1)
df_transactions = df_transactions.drop('ea_merchant_country' , axis = 1)

In [ ]:
df_transactions.isnull().sum()

transaction_id                 0
transactions_type              0
transactions_currency          0
amount_usd                     0
transactions_state             0
ea_cardholderpresence    1170594
direction                      0
user_id                        0
created_date                   0
dtype: int64

### 1.4 Users table

In [ ]:
# importing the users table from google big query

query = "SELECT * FROM  `data-analytics-bootcamp-363212.neo_bank.users`"
df_users = pd.read_gbq(query, project_id="data-analytics-bootcamp-363212")

In [ ]:
# converting the ['created_date'] from Timestamp to datetime

df_users['created_date'] = pd.to_datetime(df_users['created_date'])

# Extract date only
df_users['created_date'] = df_users['created_date'].dt.date

df_users

,user_id,birth_year,country,city,created_date,user_settings_crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_contacts,num_referrals,num_successful_referrals
0,user_2811,1988,IE,C,2018-03-04,0,STANDARD,NaN,NaN,0,0,0
1,user_4750,1987,FR,Ry,2018-04-07,0,STANDARD,NaN,NaN,0,0,0
2,user_17686,1984,GB,Ayr,2018-12-04,0,PREMIUM,NaN,NaN,6,0,0
3,user_18779,1965,GB,Ayr,2018-12-31,0,STANDARD,NaN,NaN,0,0,0
4,user_7823,1999,PL,Buk,2018-06-07,0,STANDARD,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19425,user_10774,1971,LT,Stupuru kaimas Joniskio raj.,2018-08-10,0,STANDARD,1.0,1.0,0,0,0
19426,user_13408,1997,LT,"Akademijos mstl., Kauno rajonas",2018-10-12,0,STANDARD,1.0,1.0,0,0,0
19427,user_7913,1980,LT,"SangrÅ«dos km., Kalvarijos sav.",2018-06-23,0,STANDARD,1.0,1.0,0,0,0
19428,user_5542,1981,ES,San Isidro - Granadilla de Abona,2018-05-16,0,STANDARD,1.0,1.0,0,0,0
19429,user_18093,1983,CZ,DobrÃ¡ Voda u ÄŒeskÃ½ch BudÄ›jovic,2018-12-07,0,STANDARD,1.0,1.0,10,0,0

In [ ]:
df_users.isnull().sum()

user_id                                        0
birth_year                                     0
country                                        0
city                                           0
created_date                                   0
user_settings_crypto_unlocked                  0
plan                                           0
attributes_notifications_marketing_push     6610
attributes_notifications_marketing_email    6610
num_contacts                                   0
num_referrals                                  0
num_successful_referrals                       0
dtype: int64

#### cleaning some columns in my the user table:

In [ ]:
df_users.head()

,user_id,birth_year,country,city,created_date,user_settings_crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_contacts,num_referrals,num_successful_referrals
0,user_2811,1988,IE,C,2018-03-04,0,STANDARD,NaN,NaN,0,0,0
1,user_4750,1987,FR,Ry,2018-04-07,0,STANDARD,NaN,NaN,0,0,0
2,user_17686,1984,GB,Ayr,2018-12-04,0,PREMIUM,NaN,NaN,6,0,0
3,user_18779,1965,GB,Ayr,2018-12-31,0,STANDARD,NaN,NaN,0,0,0
4,user_7823,1999,PL,Buk,2018-06-07,0,STANDARD,NaN,NaN,0,0,0

In [ ]:
#1 droping the 'city' column:
df_users = df_users.drop('city' , axis = 1 )

In [ ]:
#2 changing the 'user_settings_crypto_unlocked' column name:
df_users = df_users.rename(columns={'user_settings_crypto_unlocked' : 'crypto_unlocked'})

In [ ]:
#3 creating a new column to group the conacts in one column:
def get_contact_group(num_contacts):
    if num_contacts >= 0 and num_contacts <= 10:
        return '0-10'
    elif num_contacts > 11 and num_contacts <= 50:
        return '11-50'
    elif num_contacts > 50 and num_contacts <= 200:
        return '51-200'
    elif num_contacts > 200 and num_contacts <= 500:
        return '201-500'
    else:
        return 'more than 500'

df_users['contact_group'] = df_users['num_contacts'].apply(get_contact_group)

In [ ]:
#4 droping the 'num_contacts' column:
df_users = df_users.drop('num_contacts' , axis = 1 )

In [ ]:
df_users.head()

,user_id,birth_year,country,created_date,crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_referrals,num_successful_referrals,contact_group
0,user_2811,1988,IE,2018-03-04,0,STANDARD,NaN,NaN,0,0,0-10
1,user_4750,1987,FR,2018-04-07,0,STANDARD,NaN,NaN,0,0,0-10
2,user_17686,1984,GB,2018-12-04,0,PREMIUM,NaN,NaN,0,0,0-10
3,user_18779,1965,GB,2018-12-31,0,STANDARD,NaN,NaN,0,0,0-10
4,user_7823,1999,PL,2018-06-07,0,STANDARD,NaN,NaN,0,0,0-10

#3. Merging ðŸ§©:

## 3.1 merging the users table & the transaction table on the user type:

In [ ]:
########### This merge can be done after calculating the user_type column in the {Metrics} section ################
########## DO NOT run it now ############################
df_user_info = pd.merge(df_users, df_transactions[['user_id', 'user_type']], on='user_id', how='left')

# Drop duplicates based on "user_id"
df_user_info.drop_duplicates(subset='user_id', inplace=True)

print(df_user_info)

            user_id  birth_year country created_date  crypto_unlocked  \
0         user_2811        1988      IE   2018-03-04                0
69        user_4750        1987      FR   2018-04-07                0
153      user_17686        1984      GB   2018-12-04                0
347      user_18779        1965      GB   2018-12-31                0
349       user_7823        1999      PL   2018-06-07                0
...             ...         ...     ...          ...              ...
2740594  user_10774        1971      LT   2018-08-10                0
2740595  user_13408        1997      LT   2018-10-12                0
2740596   user_7913        1980      LT   2018-06-23                0
2740607   user_5542        1981      ES   2018-05-16                0
2740627  user_18093        1983      CZ   2018-12-07                0

             plan  attributes_notifications_marketing_push  \
0        STANDARD                                      NaN
69       STANDARD                                      NaN
153       PREMIUM                                      NaN
347      STANDARD                                      NaN
349      STANDARD                                      NaN
...           ...                                      ...
2740594  STANDARD                                      1.0
2740595  STANDARD                                      1.0
2740596  STANDARD                                      1.0
2740607  STANDARD                                      1.0
2740627  STANDARD                                      1.0

         attributes_notifications_marketing_email  num_referrals  \
0                                             NaN              0
69                                            NaN              0
153                                           NaN              0
347                                           NaN              0
349                                           NaN              0
...                                           ...            ...
2740594                                       1.0              0
2740595                                       1.0              0
2740596                                       1.0              0
2740607                                       1.0              0
2740627                                       1.0              0

         num_successful_referrals contact_group        user_type
0                               0          0-10  Non Active User
69                              0          0-10  Non Active User
153                             0          0-10     At Risk user
347                             0          0-10     At Risk user
349                             0          0-10     At Risk user
...                           ...           ...              ...
2740594                         0          0-10              NaN
2740595                         0          0-10              NaN
2740596                         0          0-10  Non Active User
2740607                         0          0-10  Non Active User
2740627                         0          0-10     Regular User

[19430 rows x 12 columns]

In [ ]:
df_user_info.isnull().sum()

user_id                                        0
birth_year                                     0
country                                        0
created_date                                   0
crypto_unlocked                                0
plan                                           0
attributes_notifications_marketing_push     6610
attributes_notifications_marketing_email    6610
num_referrals                                  0
num_successful_referrals                       0
contact_group                                  0
user_type                                    664
dtype: int64

## 3.2 merging the devices table and the users table on the brand:

In [ ]:
# merging the two tables only on the brand:
df_user_info = pd.merge(df_user_info, df_devices[['user_id', 'brand']], on='user_id', how='left')
df_user_info

,user_id,birth_year,country,created_date,crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_referrals,num_successful_referrals,contact_group,user_type,brand
0,user_2811,1988,IE,2018-03-04,0,STANDARD,NaN,NaN,0,0,0-10,Non Active User,Apple
1,user_4750,1987,FR,2018-04-07,0,STANDARD,NaN,NaN,0,0,0-10,Non Active User,Android
2,user_17686,1984,GB,2018-12-04,0,PREMIUM,NaN,NaN,0,0,0-10,At Risk user,Apple
3,user_18779,1965,GB,2018-12-31,0,STANDARD,NaN,NaN,0,0,0-10,At Risk user,Apple
4,user_7823,1999,PL,2018-06-07,0,STANDARD,NaN,NaN,0,0,0-10,At Risk user,Apple
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19425,user_10774,1971,LT,2018-08-10,0,STANDARD,1.0,1.0,0,0,0-10,NaN,Android
19426,user_13408,1997,LT,2018-10-12,0,STANDARD,1.0,1.0,0,0,0-10,NaN,Android
19427,user_7913,1980,LT,2018-06-23,0,STANDARD,1.0,1.0,0,0,0-10,Non Active User,Android
19428,user_5542,1981,ES,2018-05-16,0,STANDARD,1.0,1.0,0,0,0-10,Non Active User,Android
19429,user_18093,1983,CZ,2018-12-07,0,STANDARD,1.0,1.0,0,0,0-10,Regular User,Android

## 3.3 performing a merge for the AB testing

In [ ]:
# Perform the inner join on 'user_id'
df_merged_transactions_users = pd.merge(df_transactions, df_users, on='user_id', how='inner')
# Display the result
df_merged_transactions_users

,transaction_id,transactions_type,transactions_currency,amount_usd,transactions_state,ea_cardholderpresence,direction,user_id,created_date_x,birth_year,country,created_date_y,crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_referrals,num_successful_referrals,contact_group
0,transaction_1973,TOPUP,AED,6079.39,COMPLETED,None,INBOUND,user_4773,2018-08-13,1983,GB,2018-04-06,1,PREMIUM,1.0,1.0,0,0,0-10
1,transaction_508,TOPUP,AED,298.64,COMPLETED,None,INBOUND,user_4773,2018-09-06,1983,GB,2018-04-06,1,PREMIUM,1.0,1.0,0,0,0-10
2,transaction_33,TOPUP,AED,236.63,COMPLETED,None,INBOUND,user_4773,2018-10-04,1983,GB,2018-04-06,1,PREMIUM,1.0,1.0,0,0,0-10
3,transaction_34,CARD_PAYMENT,AED,5.60,COMPLETED,FALSE,OUTBOUND,user_4773,2018-10-01,1983,GB,2018-04-06,1,PREMIUM,1.0,1.0,0,0,0-10
4,transaction_1018,CARD_PAYMENT,AED,6.02,COMPLETED,FALSE,OUTBOUND,user_4773,2018-10-01,1983,GB,2018-04-06,1,PREMIUM,1.0,1.0,0,0,0-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2740070,transaction_297003,TOPUP,PLN,19.88,COMPLETED,None,INBOUND,user_9649,2018-09-14,1964,PL,2018-07-12,0,STANDARD,1.0,1.0,0,0,51-200
2740071,transaction_370954,TRANSFER,PLN,0.20,COMPLETED,None,OUTBOUND,user_4431,2018-04-03,1961,PL,2018-04-02,0,STANDARD,1.0,1.0,0,0,0-10
2740072,transaction_2128247,FEE,RON,5.37,COMPLETED,None,OUTBOUND,user_14735,2019-04-19,1979,RO,2018-10-16,0,PREMIUM,1.0,1.0,0,0,51-200
2740073,transaction_2125336,TRANSFER,RON,17.90,COMPLETED,None,INBOUND,user_14735,2019-04-05,1979,RO,2018-10-16,0,PREMIUM,1.0,1.0,0,0,51-200
2740074,transaction_1923567,TOPUP,RON,0.18,FAILED,None,INBOUND,user_14714,2018-10-15,1990,RO,2018-10-14,0,STANDARD,1.0,1.0,0,0,0-10

# 4. Hypothses ðŸ’¡:

### A/B testing (H1) Users who receive less notifications are less likely to stay

In [ ]:
control_group = df_merged_transactions_users[(df_merged_transactions_users['attributes_notifications_marketing_push'] == 0) & (df_merged_transactions_users['attributes_notifications_marketing_email'] == 0)]
test_group = df_merged_transactions_users[(df_merged_transactions_users['attributes_notifications_marketing_push'] == 1) & (df_merged_transactions_users['attributes_notifications_marketing_email'] == 1)]


control_transactions = control_group['transaction_id'].count()
test_transactions = test_group['transaction_id'].count()
control_spend = control_group['amount_usd'].sum()
test_spend = test_group['amount_usd'].sum()

#_____

t_stat, p_value = stats.ttest_ind(control_group['amount_usd'], test_group['amount_usd'])

print("Control Group:")
print("Transactions:", control_transactions)
print("Total Spend:", control_spend)

print("Test Group:")
print("Transactions:", test_transactions)
print("Total Spend:", test_spend)

print("Statistical Analysis:")
print("t-statistic:", t_stat)
print("p-value:", p_value)

Control Group:
Transactions: 111898
Total Spend: 332270950.2899999
Test Group:
Transactions: 1715086
Total Spend: 163987828290.8999
Statistical Analysis:
t-statistic: -0.6016021750396058
p-value: 0.5474390553829165

* Result:
As p_value greater than 0.05 we can not reject that Users who receive less notifications are less likely to stay

# 5. Metrics ðŸ§®:

## User type - Transaction table

In [ ]:
############################### Calculation the user_type ###################################
# Assuming you have a DataFrame called 'df' with a 'created_date' column
# Convert 'created_date' column to datetime if it's not already in datetime format
df_transactions['created_date'] = pd.to_datetime(df_transactions['created_date'])

# Define the last date as 2019-05-16
last_date = pd.to_datetime('2019-05-16')

# Calculate the difference between the last date and 'created_date' column
df_transactions['activity_duration'] = (last_date - df_transactions['created_date']).dt.days

# Create a new column 'user_category' based on the activity duration
df_transactions['user_type'] = pd.cut(df_transactions['activity_duration'], bins=[-1, 30, 90, 180, float('inf')], labels=['Very Active User', 'Regular User', 'At Risk user', 'Non Active User'])

# Print the updated DataFrame
print(df_transactions)

              transaction_id transactions_type transactions_currency  \
0           transaction_1973             TOPUP                   AED
1            transaction_508             TOPUP                   AED
2             transaction_33             TOPUP                   AED
3        transaction_1755306          EXCHANGE                   AED
4            transaction_940          EXCHANGE                   AED
...                      ...               ...                   ...
2740070  transaction_1846709      CARD_PAYMENT                   ZAR
2740071    transaction_89487      CARD_PAYMENT                   ZAR
2740072   transaction_227881      CARD_PAYMENT                   ZAR
2740073    transaction_88782      CARD_PAYMENT                   ZAR
2740074  transaction_1846020      CARD_PAYMENT                   ZAR

         amount_usd transactions_state ea_cardholderpresence direction  \
0           6079.39          COMPLETED                  None   INBOUND
1            298.64          COMPLETED                  None   INBOUND
2            236.63          COMPLETED                  None   INBOUND
3             69.92          COMPLETED                  None  OUTBOUND
4             52.24          COMPLETED                  None  OUTBOUND
...             ...                ...                   ...       ...
2740070      651.84           DECLINED                  TRUE  OUTBOUND
2740071        7.14          COMPLETED                  TRUE  OUTBOUND
2740072       12.69          COMPLETED                 FALSE  OUTBOUND
2740073        3.44          COMPLETED                  TRUE  OUTBOUND
2740074        7.51          COMPLETED                 FALSE  OUTBOUND

            user_id created_date  activity_duration        user_type
0         user_4773   2018-08-13                276  Non Active User
1         user_4773   2018-09-06                252  Non Active User
2         user_4773   2018-10-04                224  Non Active User
3        user_10943   2018-12-07                160     At Risk user
4         user_1363   2018-12-28                139     At Risk user
...             ...          ...                ...              ...
2740070  user_10000   2018-08-20                269  Non Active User
2740071    user_598   2018-11-21                176     At Risk user
2740072   user_1051   2018-10-01                227  Non Active User
2740073    user_598   2018-11-21                176     At Risk user
2740074  user_19085   2019-04-05                 41     Regular User

[2740075 rows x 11 columns]

# 6. Our data ðŸ’¾:

In [ ]:
df_user_info

,user_id,birth_year,country,created_date,crypto_unlocked,plan,attributes_notifications_marketing_push,attributes_notifications_marketing_email,num_referrals,num_successful_referrals,contact_group,user_type,brand
0,user_2811,1988,IE,2018-03-04,0,STANDARD,NaN,NaN,0,0,0-10,Non Active User,Apple
1,user_4750,1987,FR,2018-04-07,0,STANDARD,NaN,NaN,0,0,0-10,Non Active User,Android
2,user_17686,1984,GB,2018-12-04,0,PREMIUM,NaN,NaN,0,0,0-10,At Risk user,Apple
3,user_18779,1965,GB,2018-12-31,0,STANDARD,NaN,NaN,0,0,0-10,At Risk user,Apple
4,user_7823,1999,PL,2018-06-07,0,STANDARD,NaN,NaN,0,0,0-10,At Risk user,Apple
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19425,user_10774,1971,LT,2018-08-10,0,STANDARD,1.0,1.0,0,0,0-10,NaN,Android
19426,user_13408,1997,LT,2018-10-12,0,STANDARD,1.0,1.0,0,0,0-10,NaN,Android
19427,user_7913,1980,LT,2018-06-23,0,STANDARD,1.0,1.0,0,0,0-10,Non Active User,Android
19428,user_5542,1981,ES,2018-05-16,0,STANDARD,1.0,1.0,0,0,0-10,Non Active User,Android
19429,user_18093,1983,CZ,2018-12-07,0,STANDARD,1.0,1.0,0,0,0-10,Regular User,Android

In [ ]:
df_notifications

,reason,channel,status,user_id,created_date
0,METAL_RESERVE_PLAN,SMS,SENT,user_4703,2018-10-14
1,METAL_RESERVE_PLAN,SMS,SENT,user_2397,2018-10-17
2,METAL_RESERVE_PLAN,SMS,SENT,user_2411,2018-10-14
3,METAL_RESERVE_PLAN,SMS,SENT,user_1119,2018-10-14
4,METAL_RESERVE_PLAN,SMS,SENT,user_3499,2018-10-14
...,...,...,...,...,...
121808,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19156,2019-01-26
121809,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_18016,2019-01-26
121810,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_18016,2019-01-27
121811,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19023,2019-01-28
121812,NO_INITIAL_FREE_PROMOPAGE_CARD_ORDER,EMAIL,FAILED,user_19156,2019-01-27

# 7. saving files ðŸ“‚:

#### 1. BigQuery

In [ ]:
from google.oauth2 import service_account
import pandas_gbq

credentials = service_account.Credentials.from_service_account_file(
    '/content/ardent-bridge-400707-51d6c46528c2.json')

#### 2. User table

In [ ]:
df_user_info.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19430 entries, 0 to 19429
Data columns (total 13 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   user_id                                   19430 non-null  object
 1   birth_year                                19430 non-null  Int64
 2   country                                   19430 non-null  object
 3   created_date                              19430 non-null  object
 4   crypto_unlocked                           19430 non-null  Int64
 5   plan                                      19430 non-null  object
 6   attributes_notifications_marketing_push   12820 non-null  float64
 7   attributes_notifications_marketing_email  12820 non-null  float64
 8   num_referrals                             19430 non-null  Int64
 9   num_successful_referrals                  19430 non-null  Int64
 10  contact_group                             19430 non-null  object
 11  user_type                                 18766 non-null  category
 12  brand                                     19430 non-null  object
dtypes: Int64(4), category(1), float64(2), object(6)
memory usage: 2.0+ MB

In [ ]:
df_user_info['created_date'] = pd.to_datetime(df_user_info['created_date'])

In [ ]:
df_user_info.info()

In [ ]:
df_user_info.to_gbq('Neo_Bank.user_info', project_id='ardent-bridge-400707',credentials=credentials, if_exists='replace')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 6932.73it/s]

#### 3. Notifications table

In [ ]:
df_notifications['created_date'] = pd.to_datetime(df_notifications['created_date'])

In [ ]:
df_notifications.to_gbq('Neo_Bank.notifications', project_id='ardent-bridge-400707',credentials=credentials, if_exists='replace')

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 1328.57it/s]